### ISSUE TITLE
Reporting forms for Facilitator Data Collection

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-mx-content#15]
Initial deployment of Facilitator App in Mexico includes only 2 reporting forms (1 for in-person onboarding, another for remote whatsapp support). Both forms are available to all faciltators and largely carry the same package as global reporting forms. Fidelity questions will be updated in the data list, but there is an additional question added to the remote whatsapp reporting form. [See here.](https://docs.google.com/document/d/1QXnbuvzXCCPS6_5gsYzrJE52wTgVldeOHJAENhev3Qk/edit?usp=sharing)

**Comment by esmeetewinkel** [comment]
Additional question has been removed, closing here
