### ISSUE TITLE
UAT preview

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/plh-facilitator-app-mx-content#49]
When preparing the app for Scale Up, we need separate previews for testing and for deploying 

https://plh-facilitator-mx.web.app/ deploying - stable / static
https://plh-facilitator-mx-uat.web.app/ testing

**Comment by ChrisMarsh82** [comment]
New action to run when deploying stable/static release 
https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/actions/workflows/firebase-release.yml
@esmeetewinkel
